[signer_pool]
strategy = "round_robin"

[[signers]]
name = "local_payer"
# This defines the fee payer wallet that the Kora node uses
type = "memory"
weight = 1
# Load the strict key mapping directly from the CLI environment
private_key_env = "KORA_SPONSOR_PRIVATE_KEY"
